### ISSUE TITLE
argparse.ArgumentError: argument --password/-p: conflicting option string: -p

### ISSUE THREAD

**Issue by tmeekes** [chrisrosset/mamaroo-mqtt#4]
I keep getting a password argument error... albeit, I've tried installing this in a way that's different from instructed (using HA Core and creating my own docker container for this code)

argparse.ArgumentError: argument --password/-p: conflicting option string: -p

**Comment by chrisrosset** [comment]
Ah, there's a bug in the command line parser. I'll try to post a fix soon.

In the meantime, you could edit line 172 to simply remove the "-p" argument
or replace it with, for example, "-r".

**Comment by chrisrosset** [comment]
Could you please try pulling the latest version and giving it a go?
