### ISSUE TITLE
HA-side configuration?

### ISSUE THREAD

**Issue by arifeinberg** [chrisrosset/mamaroo-mqtt#5]
Does this require any configuration on the Home Assistant side?  I have MQTT running, and mamaroo-mqtt seems to connect okay, but no entities appear.

**Comment by chrisrosset** [comment]
Do you have the MQTT integration enabled in HA?

If yes, do you have discovery enabled?
https://www.home-assistant.io/docs/mqtt/discovery/#configuration

**Comment by AndrewDarlington** [comment]
Thank you for writing this! But I'm having the same issue. I do have MQTT running with discovery enabled. I followed the installation instructions and it finished with no errors or warnings. But I don't see any new entities. I'd like to check my entities to be 100% sure they're not there -- can you tell me what they'd be named so I can search for them?

**Comment by chrisrosset** [comment]
Here are screenshots from my Devices and Entities tabs:

![devices](https://user-images.githubusercontent.com/1103294/184349877-0917088f-c7d6-401d-818d-f35250391c3f.png)
![entities](https://user-images.githubusercontent.com/1103294/184349947-b9dfb419-e8f4-4601-9ebe-0424eb7f27a4.png)

Can you see anything connecting to the MQTT broker? Could you post docker logs?

**Comment by AndrewDarlington** [comment]
Hi - I'm home now with a newborn baby, so haven't been doing any tinkering lately. Once I have a sec to dive back in, I'll take a look and post docker logs. Just to confirm: in the docker command (step 8 of your instructions), the username/pwd are for MQTT, not the mamaRoo app, right? (I tried both ways, and didn't have success either way, but just want to make sure I'm doing that part correctly.)

**Comment by chrisrosset** [comment]
Correct, they are the MQTT credentials.
